# Generated by Django 4.1.5 on 2023-01-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arquivo", "0002_arquivo_cartao_arquivo_cpf_arquivo_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arquivo",
            name="cartao",
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name="arquivo",
            name="cpf",
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name="arquivo",
            name="data",
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name="arquivo",
            name="dono_loja",
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name="arquivo",
            name="hora",
            field=models.TimeField(default="00:00:00"),
        ),
        migrations.AlterField(
            model_name="arquivo",
            name="nome_loja",
            field=models.CharField(max_length=19),
        ),
        migrations.AlterField(
            model_name="arquivo",
            name="tipo",
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name="arquivo",
            name="valor",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
